import { ArrowRight, CalendarDays, CircleCheck, Dumbbell, Plus, Utensils, Waves } from "lucide-react";
import { Link } from "react-router";
import { AppShell } from "@/components/AppShell";
import { Seo } from "@/components/Seo";
import { useSupabaseAuth } from "@/hooks/use-supabase-auth";
import { useKovaPlans, useKovaProfile } from "@/hooks/use-kova-app";

function Widget({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`liquid-glass rounded-[1.5rem] border-white/[0.1] bg-white/[0.035] p-5 ${className}`}>{children}</section>; }
function Label({ children }: { children: React.ReactNode }) { return <p className="text-[10px] font-medium uppercase tracking-[0.2em] text-white/35">{children}</p>; }

export default function AppDashboard() {
  const { user } = useSupabaseAuth();
  const { plans, isLoading: plansLoading } = useKovaPlans(user?.id);
  const { profile } = useKovaProfile(user?.id);
  const activePlan = plans.find((plan) => plan.status === "active") ?? plans[0];
  const name = profile?.display_name || user?.user_metadata?.display_name || "there";

  return <AppShell><Seo title="Home — KOVA AI" description="Your personal KOVA AI training workspace." path="/dashboard" /><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Label>Today · {new Date().toLocaleDateString(undefined, { weekday: "long", month: "short", day: "numeric" })}</Label><h1 className="mt-3 font-serif text-[clamp(2.8rem,6vw,5rem)] italic leading-[0.9] tracking-[-0.07em]">Good to see you, {name.split(" ")[0]}.</h1><p className="mt-4 max-w-lg text-sm leading-6 text-white/45">{activePlan ? "Your plan is ready. Here is what is next." : "Start with one clear next step. KOVA will build from there."}</p></div><Link to="/dashboard/plan" className="group inline-flex h-11 items-center justify-center gap-3 rounded-full bg-white px-5 text-xs font-semibold uppercase tracking-[0.12em] text-black transition-transform hover:scale-[1.02]">{activePlan ? "View plan" : "Create plan"}<ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" /></Link></div>
    {!plansLoading && !activePlan ? <section className="relative mt-10 overflow-hidden rounded-[2rem] border border-white/[0.14] bg-white/[0.055] p-6 sm:p-10"><div className="pointer-events-none absolute right-0 top-0 size-72 rounded-full bg-white/[0.06] blur-[80px]" /><div className="relative max-w-xl"><div className="flex size-12 items-center justify-center rounded-2xl bg-white text-black"><Plus className="size-5" /></div><h2 className="mt-7 font-serif text-4xl italic tracking-[-0.06em] sm:text-5xl">Create your first plan.</h2><p className="mt-4 text-sm leading-7 text-white/50">Tell KOVA how you train, what you want to achieve and what equipment you can use. You can skip anything you do not know yet.</p><Link to="/dashboard/plan?create=1" className="mt-8 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-white hover:text-white/65">Start plan maker <ArrowRight className="size-4" /></Link></div></section> : <div className="mt-10 grid gap-4 lg:grid-cols-[1.35fr_0.65fr]"><Widget className="min-h-[260px]"><Label>Next up</Label><div className="mt-7 flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.16em] text-white/35">Plan</p><h2 className="mt-2 font-serif text-4xl italic tracking-[-0.05em]">{activePlan?.name}</h2><p className="mt-3 text-sm text-white/45">Your plan is saved. Add workout days to start your first session.</p></div><span className="flex size-11 items-center justify-center rounded-2xl bg-white/[0.08]"><Dumbbell className="size-5 text-white/70" /></span></div><Link to="/dashboard/plan" className="mt-10 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-white">Open plan <ArrowRight className="size-4" /></Link></Widget><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><Widget><Label>Recovery</Label><div className="mt-5 flex items-center gap-3"><Waves className="size-5 text-white/55" /><p className="text-sm text-white/55">No recovery data yet.</p></div></Widget><Widget><Label>Nutrition</Label><div className="mt-5 flex items-center gap-3"><Utensils className="size-5 text-white/55" /><p className="text-sm text-white/55">Set your targets in Food.</p></div></Widget></div></div>}
    <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Widget><Label>Weekly schedule</Label><div className="mt-5 flex items-center gap-3"><CalendarDays className="size-5 text-white/45" /><p className="text-sm text-white/45">{activePlan ? "No days added yet." : "Create a plan first."}</p></div></Widget><Widget><Label>Progress</Label><div className="mt-5 flex items-center gap-3"><CircleCheck className="size-5 text-white/45" /><p className="text-sm text-white/45">No workouts logged.</p></div></Widget><Widget><Label>Selected gym</Label><p className="mt-5 text-sm text-white/45">No gym selected.</p></Widget><Widget><Label>Current plan</Label><p className="mt-5 truncate text-sm text-white/45">{activePlan?.name ?? "None yet"}</p></Widget></div>
  </div></AppShell>;
}
