import { useEffect, useState } from "react";
import { Check, ExternalLink, Loader2, Lock, Moon, Save, Sun, UserRound } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Seo } from "@/components/Seo";
import { useSupabaseAuth } from "@/hooks/use-supabase-auth";
import { useKovaPlans, useKovaProfile } from "@/hooks/use-kova-app";

function EmptySection({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mx-auto max-w-7xl"><p className="eyebrow">{eyebrow}</p><h1 className="mt-3 font-serif text-6xl italic tracking-[-0.08em]">{title}</h1><p className="mt-5 max-w-lg text-sm leading-7 text-white/45">{description}</p><div className="mt-10 rounded-[1.5rem] border border-white/10 bg-white/[0.03] p-7 sm:p-10"><Lock className="size-5 text-white/40" /><h2 className="mt-6 font-serif text-3xl italic">Nothing to show yet.</h2><p className="mt-3 max-w-md text-sm leading-6 text-white/40">Once you create a plan and log real sessions, this space will reflect your training. KOVA will never fill it with placeholder numbers.</p></div></div>; }

export function Food() { return <AppShell><Seo title="Food — KOVA AI" description="Simple nutrition guidance connected to your KOVA plan." path="/dashboard/food" /><EmptySection eyebrow="Nutrition" title="Food." description="Keep nutrition simple, useful and connected to the way you train." /></AppShell>; }
export function Progress() { return <AppShell><Seo title="Progress — KOVA AI" description="Understand your real KOVA AI training progress." path="/dashboard/progress" /><EmptySection eyebrow="Your history" title="Progress." description="Your meaningful changes will live here: completed workouts, strength, consistency and more." /></AppShell>; }

export function Profile() {
  const { user } = useSupabaseAuth();
  const { profile, isLoading, update } = useKovaProfile(user?.id);
  const [displayName, setDisplayName] = useState(""); const [username, setUsername] = useState(""); const [bio, setBio] = useState(""); const [isPublic, setIsPublic] = useState(false); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (profile) { setDisplayName(profile.display_name ?? ""); setUsername(profile.username ?? ""); setBio(profile.bio ?? ""); setIsPublic(profile.is_public); } }, [profile]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setSaved(false); try { await update({ display_name: displayName.trim() || null, username: username.trim().toLowerCase() || null, bio: bio.trim() || null, is_public: isPublic }); setSaved(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save profile."); } finally { setSaving(false); } };
  return <AppShell><Seo title="Profile — KOVA AI" description="Manage your KOVA AI profile." path="/dashboard/profile" /><div className="mx-auto max-w-3xl"><p className="eyebrow">Your identity</p><h1 className="mt-3 font-serif text-6xl italic tracking-[-0.08em]">Profile.</h1><p className="mt-5 text-sm leading-7 text-white/45">Control what KOVA knows about you and what other people can see.</p><form onSubmit={save} className="mt-10 space-y-4"><div className="flex items-center gap-4 rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5"><span className="flex size-14 items-center justify-center rounded-full bg-white text-xl text-black">{(displayName || user?.email || "K").slice(0, 1).toUpperCase()}</span><div><p className="text-sm text-white/75">{user?.email}</p><p className="mt-1 text-xs text-white/35">Your login email</p></div></div><label className="block"><span className="mb-2 block text-xs text-white/45">Display name</span><input value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="How should KOVA call you?" className="h-12 w-full rounded-2xl border border-white/10 bg-white/[0.035] px-4 text-sm text-white outline-none placeholder:text-white/25 focus:border-white/30" /></label><label className="block"><span className="mb-2 block text-xs text-white/45">Username</span><input value={username} onChange={(e) => setUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g, ""))} placeholder="your-username" className="h-12 w-full rounded-2xl border border-white/10 bg-white/[0.035] px-4 text-sm text-white outline-none placeholder:text-white/25 focus:border-white/30" /></label><label className="block"><span className="mb-2 block text-xs text-white/45">Bio</span><textarea value={bio} onChange={(e) => setBio(e.target.value)} placeholder="A little about your training" className="min-h-28 w-full resize-y rounded-2xl border border-white/10 bg-white/[0.035] p-4 text-sm text-white outline-none placeholder:text-white/25 focus:border-white/30" /></label><label className="flex cursor-pointer items-center justify-between rounded-2xl border border-white/10 bg-white/[0.035] p-4"><span><span className="block text-sm text-white/70">Public profile</span><span className="mt-1 block text-xs text-white/35">Allow people to find your profile and public plans.</span></span><input type="checkbox" checked={isPublic} onChange={(e) => setIsPublic(e.target.checked)} className="size-4 accent-white" /></label>{error && <p className="text-sm text-red-200">{error}</p>}{saved && <p className="flex items-center gap-2 text-sm text-white/60"><Check className="size-4" />Profile saved.</p>}<button type="submit" disabled={saving || isLoading} className="inline-flex h-11 items-center gap-2 rounded-full bg-white px-5 text-xs font-semibold uppercase tracking-[0.12em] text-black disabled:opacity-50">{saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}Save profile</button></form></div></AppShell>;
}

export function Settings() {
  const [theme, setTheme] = useState(() => localStorage.getItem("kova-theme") ?? "dark");
  const changeTheme = (value: string) => { setTheme(value); localStorage.setItem("kova-theme", value); document.documentElement.classList.toggle("light", value === "light"); };
  return <AppShell><Seo title="Settings — KOVA AI" description="Manage your KOVA AI app settings." path="/dashboard/settings" /><div className="mx-auto max-w-3xl"><p className="eyebrow">Workspace</p><h1 className="mt-3 font-serif text-6xl italic tracking-[-0.08em]">Settings.</h1><div className="mt-10 divide-y divide-white/10 rounded-[1.5rem] border border-white/10 bg-white/[0.03]"><div className="p-6"><p className="text-sm font-medium text-white/75">Appearance</p><p className="mt-1 text-sm text-white/35">Choose how KOVA looks on this device.</p><div className="mt-5 flex flex-wrap gap-2">{[["dark", Moon], ["light", Sun], ["system", UserRound]].map(([value, Icon]) => <button key={value as string} type="button" onClick={() => changeTheme(value as string)} className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-xs capitalize transition-colors ${theme === value ? "border-white bg-white text-black" : "border-white/10 text-white/50 hover:text-white"}`}><Icon className="size-3.5" />{value as string}</button>)}</div></div><div className="p-6"><p className="text-sm font-medium text-white/75">Training</p><p className="mt-1 text-sm leading-6 text-white/35">Your plan maker will use your availability, space and preferences. Change these from your Plan when you are ready.</p></div><div className="p-6"><p className="text-sm font-medium text-white/75">Gym</p><p className="mt-1 text-sm text-white/35">No gym selected yet.</p></div></div></div></AppShell>;
}

export function Upgrade() { return <AppShell><Seo title="Upgrade — KOVA AI" description="KOVA AI plans and subscription options." path="/dashboard/upgrade" /><div className="mx-auto max-w-5xl"><p className="eyebrow">KOVA membership</p><h1 className="mt-3 font-serif text-6xl italic tracking-[-0.08em]">Upgrade.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-white/45">Choose the level of coaching that fits you. Subscription status and payments will only appear here once they are connected to a verified billing account.</p><div className="mt-10 grid gap-4 md:grid-cols-3">{["Free", "Pro", "Max"].map((name) => <article key={name} className="rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-6"><p className="text-[10px] uppercase tracking-[0.18em] text-white/30">KOVA</p><h2 className="mt-8 font-serif text-4xl italic">{name}</h2><p className="mt-4 text-sm leading-6 text-white/40">Plan details will be shown from the connected billing provider.</p><span className="mt-8 inline-flex items-center gap-2 text-xs uppercase tracking-[0.12em] text-white/35">Not active <ExternalLink className="size-3" /></span></article>)}</div></div></AppShell>; }
